import {documentIngestion} from "../documentIngestion/composition";
import {continueTrace,observe,pseudonym,safeErrorCode,safeLog,telemetryMetrics} from "../../shared/observability/safeTelemetry";
import type {QueueMessage} from "./domain";
import {chainConversationExtraction} from "../conversations/segmentExtraction";
export const handleSourceSecurity=async(message:QueueMessage)=>continueTrace(message.traceparent,async()=>{const started=Date.now();const labels={jobId:message.jobId,jobType:message.jobType,correlationId:message.correlationId,organizationPseudonym:pseudonym(message.organizationMongoId)};safeLog("info","job.execution.started",labels);try{return await observe("job.source_security_scan",{jobType:message.jobType},async()=>{const source=await documentIngestion.scan({organizationMongoId:message.organizationMongoId,userMongoId:message.actorUserMongoId,sourceId:message.inputReference,correlationId:message.correlationId});if(source.status==="scan_failed")throw Object.assign(new Error("Scanner dependency unavailable"),{code:"SCANNER_UNAVAILABLE",retryable:true});// A transcript segment has no "extract this" button, so the scan that
// clears it starts the run. Never allowed to fail the scan job: a clean
// source the planner can still extract manually beats losing the source.
await chainConversationExtraction({source,organizationMongoId:message.organizationMongoId,actorUserMongoId:message.actorUserMongoId,correlationId:message.correlationId});
if(!["ready","blocked"].includes(source.status))throw Object.assign(new Error("Unexpected source state"),{code:"SOURCE_STATE_INVALID",retryable:false});safeLog("info","job.execution.completed",{...labels,outcome:"success",durationMs:Date.now()-started});telemetryMetrics.job("success",Date.now()-started,{jobType:message.jobType});return{resultReference:source.id,status:source.status};});}catch(error){const errorCode=safeErrorCode(error);safeLog("error","job.execution.failed",{...labels,outcome:"failure",errorCode,durationMs:Date.now()-started});telemetryMetrics.job("failure",Date.now()-started,{jobType:message.jobType,errorCode});throw error;}});
