CREATE TABLE rfpilot.candidate_review_sets(
 id uuid PRIMARY KEY,organization_id uuid NOT NULL REFERENCES rfpilot.organizations(id) ON DELETE RESTRICT,run_id uuid NOT NULL REFERENCES rfpilot.proposal_context_runs(id) ON DELETE RESTRICT,proposal_reference_id uuid NOT NULL REFERENCES rfpilot.proposal_references(id) ON DELETE RESTRICT,actor_external_user_id varchar(24) NOT NULL CHECK(actor_external_user_id~'^[0-9a-f]{24}$'),revision integer NOT NULL DEFAULT 1 CHECK(revision>0),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,run_id,actor_external_user_id)
);
CREATE TABLE rfpilot.candidate_review_decisions(
 id uuid PRIMARY KEY,organization_id uuid NOT NULL REFERENCES rfpilot.organizations(id) ON DELETE RESTRICT,review_set_id uuid NOT NULL REFERENCES rfpilot.candidate_review_sets(id) ON DELETE RESTRICT,operation_id uuid NOT NULL REFERENCES rfpilot.proposal_context_operations(id) ON DELETE RESTRICT,decision text NOT NULL CHECK(decision IN('pending','accepted','modified','rejected')),modified_value jsonb,modified_value_checksum char(64) CHECK(modified_value_checksum IS NULL OR modified_value_checksum~'^[0-9a-f]{64}$'),reason text CHECK(reason IS NULL OR length(reason)<=500),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(review_set_id,operation_id),CHECK((decision='modified')=(modified_value IS NOT NULL))
);
CREATE TABLE rfpilot.candidate_applications(
 id uuid PRIMARY KEY,organization_id uuid NOT NULL REFERENCES rfpilot.organizations(id) ON DELETE RESTRICT,proposal_reference_id uuid NOT NULL REFERENCES rfpilot.proposal_references(id) ON DELETE RESTRICT,run_id uuid NOT NULL REFERENCES rfpilot.proposal_context_runs(id) ON DELETE RESTRICT,review_set_id uuid NOT NULL REFERENCES rfpilot.candidate_review_sets(id) ON DELETE RESTRICT,job_id uuid NOT NULL UNIQUE REFERENCES rfpilot.ai_jobs(id) ON DELETE RESTRICT,actor_external_user_id varchar(24) NOT NULL CHECK(actor_external_user_id~'^[0-9a-f]{24}$'),status text NOT NULL CHECK(status IN('queued','validating','applying','applied','conflict','failed')),expected_proposal_version integer NOT NULL CHECK(expected_proposal_version>0),resulting_proposal_version integer,selected_count smallint NOT NULL CHECK(selected_count BETWEEN 1 AND 25),before_checksum char(64),after_checksum char(64),safe_error_code text,idempotency_key text NOT NULL CHECK(length(idempotency_key) BETWEEN 1 AND 200),correlation_id uuid NOT NULL,retention_until timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz,UNIQUE(organization_id,idempotency_key)
);
CREATE TABLE rfpilot.candidate_application_items(
 id uuid PRIMARY KEY,organization_id uuid NOT NULL REFERENCES rfpilot.organizations(id) ON DELETE RESTRICT,application_id uuid NOT NULL REFERENCES rfpilot.candidate_applications(id) ON DELETE RESTRICT,decision_id uuid NOT NULL REFERENCES rfpilot.candidate_review_decisions(id) ON DELETE RESTRICT,operation_id uuid NOT NULL REFERENCES rfpilot.proposal_context_operations(id) ON DELETE RESTRICT,ordinal smallint NOT NULL CHECK(ordinal BETWEEN 0 AND 24),canonical_path text NOT NULL CHECK(canonical_path~'^/content(?:/[A-Za-z0-9_~-]+)+$'),value_checksum char(64) NOT NULL CHECK(value_checksum~'^[0-9a-f]{64}$'),overwrite_confirmed boolean NOT NULL,outcome text NOT NULL DEFAULT 'pending' CHECK(outcome IN('pending','applied','conflict','failed')),safe_error_code text,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(application_id,operation_id),UNIQUE(application_id,ordinal)
);
CREATE INDEX candidate_reviews_run_idx ON rfpilot.candidate_review_sets(organization_id,run_id);CREATE INDEX candidate_applications_proposal_idx ON rfpilot.candidate_applications(organization_id,proposal_reference_id,created_at DESC);
ALTER TABLE rfpilot.candidate_review_sets ENABLE ROW LEVEL SECURITY;ALTER TABLE rfpilot.candidate_review_sets FORCE ROW LEVEL SECURITY;ALTER TABLE rfpilot.candidate_review_decisions ENABLE ROW LEVEL SECURITY;ALTER TABLE rfpilot.candidate_review_decisions FORCE ROW LEVEL SECURITY;ALTER TABLE rfpilot.candidate_applications ENABLE ROW LEVEL SECURITY;ALTER TABLE rfpilot.candidate_applications FORCE ROW LEVEL SECURITY;ALTER TABLE rfpilot.candidate_application_items ENABLE ROW LEVEL SECURITY;ALTER TABLE rfpilot.candidate_application_items FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_candidate_review_sets ON rfpilot.candidate_review_sets USING(organization_id=rfpilot.current_organization_id()) WITH CHECK(organization_id=rfpilot.current_organization_id());CREATE POLICY tenant_candidate_review_decisions ON rfpilot.candidate_review_decisions USING(organization_id=rfpilot.current_organization_id()) WITH CHECK(organization_id=rfpilot.current_organization_id());CREATE POLICY tenant_candidate_applications ON rfpilot.candidate_applications USING(organization_id=rfpilot.current_organization_id()) WITH CHECK(organization_id=rfpilot.current_organization_id());CREATE POLICY tenant_candidate_application_items ON rfpilot.candidate_application_items USING(organization_id=rfpilot.current_organization_id()) WITH CHECK(organization_id=rfpilot.current_organization_id());
CREATE FUNCTION rfpilot.reject_candidate_application_evidence_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'candidate application evidence is immutable';END $$;CREATE TRIGGER candidate_application_items_immutable BEFORE UPDATE OR DELETE ON rfpilot.candidate_application_items FOR EACH ROW EXECUTE FUNCTION rfpilot.reject_candidate_application_evidence_mutation();
