import crypto from"node:crypto";import ExcelJS from"exceljs";import{PDFParse}from"pdf-parse";import{KnowledgeIngestionError}from"./domain";
// eslint-disable-next-line @typescript-eslint/no-require-imports
const mammoth=require("mammoth")as{extractRawText:(v:{buffer:Buffer})=>Promise<{value:string}>};
export type SourceFragment={ordinal:number;content:string;coordinates:Record<string,string|number>;checksum:string};
export type ParseResult={parserKind:string;parserVersion:"deterministic-v1";fragments:SourceFragment[]};
const MAX_BYTES=50*1024*1024,MAX_FRAGMENTS=5000,MAX_CONTENT=50_000;
const clean=(v:string)=>v.split("\0").join("").replace(/\r\n/g,"\n").trim();
const fragment=(ordinal:number,content:string,coordinates:SourceFragment["coordinates"]):SourceFragment=>{const value=clean(content).slice(0,MAX_CONTENT);return{ordinal,content:value,coordinates,checksum:crypto.createHash("sha256").update(value.normalize("NFKC")).digest("hex")};};
const ensure=(bytes:Buffer,fragments:SourceFragment[])=>{if(!bytes.length||bytes.length>MAX_BYTES)throw new KnowledgeIngestionError("PARSER_INPUT_INVALID","Source size is invalid.",422);const safe=fragments.filter(x=>x.content);if(!safe.length)throw new KnowledgeIngestionError("EMPTY_SOURCE","No deterministic text could be extracted.",422);if(safe.length>MAX_FRAGMENTS)throw new KnowledgeIngestionError("PARSER_LIMIT_EXCEEDED","Source produces too many fragments.",413);return safe;};
const delimited=(text:string)=>{const rows:string[][]=[];let row:string[]=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===","&&!quoted){row.push(cell);cell="";}else if((c==="\n"||c==="\r")&&!quoted){if(c==="\r"&&text[i+1]==="\n")i++;row.push(cell);rows.push(row);row=[];cell="";}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}return rows;};
const cellText=(value:ExcelJS.CellValue)=>{if(value===null||value===undefined)return"";if(value instanceof Date)return value.toISOString();if(typeof value==="object"){if("formula"in value)return `[FORMULA] ${"result"in value&&value.result!==undefined?String(value.result):""}`.trim();if("text"in value)return String(value.text);if("richText"in value)return value.richText.map(x=>x.text).join("");return JSON.stringify(value);}return String(value);};
// Each approved MIME branch assigns the parser kind before returning.
// eslint-disable-next-line no-useless-assignment
export const deterministicParser={async parse(bytes:Buffer,mimeType:string):Promise<ParseResult>{let kind="",fragments:SourceFragment[]=[];if(mimeType==="application/pdf"){kind="pdf-native-text";const parser=new PDFParse({data:bytes});try{const r=await parser.getText();fragments=r.pages.map((p,i)=>fragment(i,p.text,{page:p.num}));}finally{await parser.destroy();}}else if(mimeType==="application/vnd.openxmlformats-officedocument.wordprocessingml.document"){kind="docx-native-text";const r=await mammoth.extractRawText({buffer:bytes});let start=0;fragments=clean(r.value).split(/\n{2,}/).map((v,i)=>{const f=fragment(i,v,{characterStart:start,characterEnd:start+v.length});start+=v.length+2;return f;});}else if(mimeType==="text/csv"){kind="csv";fragments=delimited(bytes.toString("utf8")).map((row,i)=>fragment(i,row.map((v,c)=>`${c+1}:${v}`).join("\n"),{row:i+1,columnStart:1,columnEnd:row.length}));}else if(mimeType==="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"){kind="xlsx";const workbook=new ExcelJS.Workbook();await workbook.xlsx.load(bytes as unknown as ExcelJS.Buffer);let ordinal=0;workbook.eachSheet(sheet=>{if(sheet.rowCount>100_000||sheet.columnCount>500)throw new KnowledgeIngestionError("PARSER_LIMIT_EXCEEDED","Spreadsheet exceeds parser limits.",413);sheet.eachRow((row,rowNumber)=>{const values:string[]=[];row.eachCell({includeEmpty:false},(cell,column)=>values.push(`${column}:${cellText(cell.value)}`));if(values.length)fragments.push(fragment(ordinal++,values.join("\n"),{sheet:sheet.name.slice(0,100),row:rowNumber,columnStart:1,columnEnd:row.cellCount}));});});}else if(mimeType==="text/plain"){kind="text";let start=0;fragments=clean(bytes.toString("utf8")).split(/\n{2,}/).map((v,i)=>{const f=fragment(i,v,{characterStart:start,characterEnd:start+v.length});start+=v.length+2;return f;});}else throw new KnowledgeIngestionError("UNSUPPORTED_PARSER","No deterministic parser is approved for this file type.",415);return{parserKind:kind,parserVersion:"deterministic-v1",fragments:ensure(bytes,fragments)};}};
