import type{PoolClient}from"pg";import{v7 as uuidv7}from"uuid";import{withPostgresTransaction}from"../../../config/postgres";import{KnowledgeIngestionError,type ImportBatch}from"./domain";
type Row={id:string;name:string;description:string|null;status:string;source_type:string;market:string|null;currency:string|null;classification:string;intended_use:string;observed_from:string|null;observed_to:string|null;notes:string|null;created_at:Date;updated_at:Date};
const map=(r:Row):ImportBatch=>({id:r.id,name:r.name,description:r.description,status:r.status,sourceType:r.source_type,market:r.market,currency:r.currency,classification:r.classification,intendedUse:r.intended_use,observedFrom:r.observed_from,observedTo:r.observed_to,notes:r.notes,createdAt:r.created_at.toISOString(),updatedAt:r.updated_at.toISOString()});
const tenant=async(c:PoolClient,external:string)=>{await c.query("SELECT set_config('app.organization_mongo_id',$1,true)",[external]);const r=await c.query<{id:string}>("SELECT id FROM rfpilot.organizations WHERE external_mongo_id=$1 AND status='active'",[external]);if(!r.rows[0])throw new KnowledgeIngestionError("ORGANIZATION_NOT_READY","Organization data foundation is unavailable.",503);await c.query("SELECT set_config('app.organization_id',$1,true)",[r.rows[0].id]);return r.rows[0].id;};
const get=async(c:PoolClient,id:string)=>{const r=await c.query<Row>("SELECT * FROM rfpilot.knowledge_import_batches WHERE id=$1",[id]);if(!r.rows[0])throw new KnowledgeIngestionError("BATCH_NOT_FOUND","Import batch was not found.",404);return r.rows[0];};
export const knowledgeBatchRepository={
 // The validator return type is the single source of truth for persistence input.
 // eslint-disable-next-line @typescript-eslint/consistent-type-imports
 create(input:{organizationMongoId:string;actorUserMongoId:string;correlationId:string;value:Omit<ReturnType<typeof import("./domain")["validateBatch"]>,never>}){return withPostgresTransaction(async c=>{const org=await tenant(c,input.organizationMongoId);const id=uuidv7(),v=input.value;const r=await c.query<Row>(`INSERT INTO rfpilot.knowledge_import_batches(id,organization_id,name,description,source_type,market,currency,classification,intended_use,observed_from,observed_to,notes,created_by_external_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`,[id,org,v.name,v.description,v.sourceType,v.market,v.currency,v.classification,v.intendedUse,v.observedFrom,v.observedTo,v.notes,input.actorUserMongoId]);await c.query(`INSERT INTO rfpilot.audit_events(id,organization_id,actor_external_user_id,action,target_type,target_id,decision,correlation_id,metadata) VALUES($1,$2,$3,'knowledge.import_batch.create','knowledge_import_batch',$4,'allowed',$5,'{}')`,[uuidv7(),org,input.actorUserMongoId,id,input.correlationId]);return map(r.rows[0]);});},
 list(org:string,limit:number){return withPostgresTransaction(async c=>{await tenant(c,org);const r=await c.query<Row>("SELECT * FROM rfpilot.knowledge_import_batches ORDER BY created_at DESC LIMIT $1",[limit]);return r.rows.map(map);});},
 find(org:string,id:string){return withPostgresTransaction(async c=>{await tenant(c,org);return map(await get(c,id));});},
 archive(input:{organizationMongoId:string;actorUserMongoId:string;correlationId:string;batchId:string}){return withPostgresTransaction(async c=>{const org=await tenant(c,input.organizationMongoId);const current=await get(c,input.batchId);if(!["draft","needs_review","failed","blocked"].includes(current.status))throw new KnowledgeIngestionError("INVALID_BATCH_STATE","This import batch cannot be archived in its current state.",409);const r=await c.query<Row>("UPDATE rfpilot.knowledge_import_batches SET status='archived',archived_at=now(),updated_at=now() WHERE id=$1 RETURNING *",[input.batchId]);await c.query(`INSERT INTO rfpilot.audit_events(id,organization_id,actor_external_user_id,action,target_type,target_id,decision,correlation_id,metadata) VALUES($1,$2,$3,'knowledge.import_batch.archive','knowledge_import_batch',$4,'allowed',$5,'{}')`,[uuidv7(),org,input.actorUserMongoId,input.batchId,input.correlationId]);return map(r.rows[0]);});}
};
